from enum import Enum


class ProviderType(str, Enum):
    """
    Enumeration of provider types.
    """
    
    SSRAG = "ssrag"
    SILICONFLOW = "siliconflow"
    BAILIAN="bailian"
    OLLAMA = "ollama"
    OPENAI = "openai"
    DEEPSEEK = "deepseek"
    OPENAI_API_COMPATIBLE = "openai_api_compatible"
    GEMINI = "gemini"
    VOLCENGINE = "volcengine"
    XINFERENCE = "xinference"
    ANTHROPIC = "anthropic"
    AZURE_OPENAI = "azure_openai"
    OPENROUTER = "openrouter"
    VLLM = "vllm"
    ZHIPUAI = "zhipuai"
    LMSTUDIO = "lmstudio"
    HUGGINGFACE_HUB = "huggingface_hub"
    JINA = "jina"
    MOONSHOT = "moonshot"
    BEDROCK = "bedrock"
    HUGGINGFACE_TEI = "huggingface_tei"
    HUNYUAN = "hunyuan"
    WENXIN = "wenxin"
    COHERE = "cohere"
    MINIMAX = "minimax"
    LOCALAI = "localai"
    X = "x"
    GPUSTACK = "gpustack"
    VERTEX_AI = "vertex_ai"
    MODELSCOPE = "modelscope"
    AZURE_AI_STUDIO = "azure_ai_studio"
    GROQ = "groq"
    OPENLLM = "openllm"
    CHATGLM = "chatglm"
    TENCENT = "tencent"
    FISHAUDIO = "fishaudio"
    LKEAP = "lkeap"
    STEPFUN = "stepfun"
    GITEE_AI = "gitee_ai"
    MISTRALAI = "mistralai"
    YI = "yi"
    BAICHUAN = "baichuan"
    NVIDIA = "nvidia"
    REPLICATE = "replicate"
    NVIDIA_NIM = "nvidia_nim"
    INFINIAI = "infiniai"
    PPIO = "ppio"
    TOGETHERAI = "togetherai"
    ZHINAO = "zhinao"
    NOMIC = "nomic"
    VOYAGE = "voyage"
    LLAMA_API = "llama-api"
    SAGEMAKER = "sagemaker"
    FIREWORKS = "fireworks"
    TRITON_INFERENCE_SERVER = "triton_inference_server"
    NOVITA = "novita"
    AIHUBMIX = "aihubmix"
    MAAS = "maas"
    MIXEDBREAD = "mixedbread"
    UPSTAGE = "upstage"
    OCI = "oci"
    PERFXCLOUD = "perfxcloud"
    VESSL_AI = "vessl_ai"
    NETMIND = "netmind"
    BURNCLOUD = "burncloud"
    FEATHERLESSAI = "featherlessai"
    LINDORMAI = "lindormai"
    IBM_WATSONX = "ibm_watsonx"
    SAMBANOVA = "sambanova"
    SOPHNET = "sophnet"
    BAIDU_QIANFAN = "baidu_qianfan"
