ROOT = "/api/ai/"
PING = "/api/ai/ping"
UPGRADE = "/api/ai/upgrade"

OPEN_HOME = "/api/ai/open/home"
OPEN_CHAT = "/api/ai/open/chat"
OPEN_COPILOT = "/api/ai/open/copilot"

ADMIN_APPS = "/api/ai/admin/apps"
ADMIN_APPS_FLOW = "/api/ai/admin/apps/flow"
ADMIN_APPS_SETTINGS = "/api/ai/admin/apps/settings"
ADMIN_APPS_MESSAGES = "/api/ai/admin/apps/messages"
ADMIN_APPS_PUBLISH = "/api/ai/admin/apps/publish"
ADMIN_APPS_MODALS_DATASET_SELECT = "/api/ai/admin/apps/modals/datasetSelect"
ADMIN_APPS_MODALS_DATASET_CONFIG = "/api/ai/admin/apps/modals/datasetConfig"
ADMIN_DATASET_DOCUMENTS = "/api/ai/admin/dataset/documents"
ADMIN_DATASET_SEGMENTS = "/api/ai/admin/dataset/segments"
ADMIN_DATASET_TESTING = "/api/ai/admin/dataset/testing"
ADMIN_DATASET_SETTINGS = "/api/ai/admin/dataset/settings"
ADMIN_DATASET_STATUS = "/api/ai/admin/dataset/status"
ADMIN_DATASET_TASKS = "/api/ai/admin/dataset/tasks"
ADMIN_SETTINGS_CONFIGS_MODELS = "/api/ai/admin/settings/configsModels"
ADMIN_SETTINGS_UTILITIES_CACHE = "/api/ai/admin/settings/utilitiesCache"
