/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SsAdminAppsIndexImport } from './routes/ss-admin/apps/index'
import { Route as OpenHomeIndexImport } from './routes/open/home/index'
import { Route as OpenCopilotIndexImport } from './routes/open/copilot/index'
import { Route as OpenChatIndexImport } from './routes/open/chat/index'
import { Route as SsAdminSettingsConfigsModelsImport } from './routes/ss-admin/settings/configsModels'
import { Route as SsAdminDatasetWriterImport } from './routes/ss-admin/dataset/writer'
import { Route as SsAdminDatasetTestingImport } from './routes/ss-admin/dataset/testing'
import { Route as SsAdminDatasetStatusImport } from './routes/ss-admin/dataset/status'
import { Route as SsAdminDatasetSettingsImport } from './routes/ss-admin/dataset/settings'
import { Route as SsAdminDatasetDocumentsImport } from './routes/ss-admin/dataset/documents'
import { Route as SsAdminAppsSettingsImport } from './routes/ss-admin/apps/settings'
import { Route as SsAdminAppsPublishImport } from './routes/ss-admin/apps/publish'
import { Route as SsAdminAppsLogsImport } from './routes/ss-admin/apps/logs'
import { Route as SsAdminAppsFlowImport } from './routes/ss-admin/apps/flow'

// Create/Update Routes

const SsAdminAppsIndexRoute = SsAdminAppsIndexImport.update({
  id: '/ss-admin/apps/',
  path: '/ss-admin/apps/',
  getParentRoute: () => rootRoute,
} as any)

const OpenHomeIndexRoute = OpenHomeIndexImport.update({
  id: '/open/home/',
  path: '/open/home/',
  getParentRoute: () => rootRoute,
} as any)

const OpenCopilotIndexRoute = OpenCopilotIndexImport.update({
  id: '/open/copilot/',
  path: '/open/copilot/',
  getParentRoute: () => rootRoute,
} as any)

const OpenChatIndexRoute = OpenChatIndexImport.update({
  id: '/open/chat/',
  path: '/open/chat/',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminSettingsConfigsModelsRoute =
  SsAdminSettingsConfigsModelsImport.update({
    id: '/ss-admin/settings/configsModels',
    path: '/ss-admin/settings/configsModels',
    getParentRoute: () => rootRoute,
  } as any)

const SsAdminDatasetWriterRoute = SsAdminDatasetWriterImport.update({
  id: '/ss-admin/dataset/writer',
  path: '/ss-admin/dataset/writer',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminDatasetTestingRoute = SsAdminDatasetTestingImport.update({
  id: '/ss-admin/dataset/testing',
  path: '/ss-admin/dataset/testing',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminDatasetStatusRoute = SsAdminDatasetStatusImport.update({
  id: '/ss-admin/dataset/status',
  path: '/ss-admin/dataset/status',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminDatasetSettingsRoute = SsAdminDatasetSettingsImport.update({
  id: '/ss-admin/dataset/settings',
  path: '/ss-admin/dataset/settings',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminDatasetDocumentsRoute = SsAdminDatasetDocumentsImport.update({
  id: '/ss-admin/dataset/documents',
  path: '/ss-admin/dataset/documents',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminAppsSettingsRoute = SsAdminAppsSettingsImport.update({
  id: '/ss-admin/apps/settings',
  path: '/ss-admin/apps/settings',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminAppsPublishRoute = SsAdminAppsPublishImport.update({
  id: '/ss-admin/apps/publish',
  path: '/ss-admin/apps/publish',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminAppsLogsRoute = SsAdminAppsLogsImport.update({
  id: '/ss-admin/apps/logs',
  path: '/ss-admin/apps/logs',
  getParentRoute: () => rootRoute,
} as any)

const SsAdminAppsFlowRoute = SsAdminAppsFlowImport.update({
  id: '/ss-admin/apps/flow',
  path: '/ss-admin/apps/flow',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ss-admin/apps/flow': {
      id: '/ss-admin/apps/flow'
      path: '/ss-admin/apps/flow'
      fullPath: '/ss-admin/apps/flow'
      preLoaderRoute: typeof SsAdminAppsFlowImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/apps/logs': {
      id: '/ss-admin/apps/logs'
      path: '/ss-admin/apps/logs'
      fullPath: '/ss-admin/apps/logs'
      preLoaderRoute: typeof SsAdminAppsLogsImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/apps/publish': {
      id: '/ss-admin/apps/publish'
      path: '/ss-admin/apps/publish'
      fullPath: '/ss-admin/apps/publish'
      preLoaderRoute: typeof SsAdminAppsPublishImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/apps/settings': {
      id: '/ss-admin/apps/settings'
      path: '/ss-admin/apps/settings'
      fullPath: '/ss-admin/apps/settings'
      preLoaderRoute: typeof SsAdminAppsSettingsImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/dataset/documents': {
      id: '/ss-admin/dataset/documents'
      path: '/ss-admin/dataset/documents'
      fullPath: '/ss-admin/dataset/documents'
      preLoaderRoute: typeof SsAdminDatasetDocumentsImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/dataset/settings': {
      id: '/ss-admin/dataset/settings'
      path: '/ss-admin/dataset/settings'
      fullPath: '/ss-admin/dataset/settings'
      preLoaderRoute: typeof SsAdminDatasetSettingsImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/dataset/status': {
      id: '/ss-admin/dataset/status'
      path: '/ss-admin/dataset/status'
      fullPath: '/ss-admin/dataset/status'
      preLoaderRoute: typeof SsAdminDatasetStatusImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/dataset/testing': {
      id: '/ss-admin/dataset/testing'
      path: '/ss-admin/dataset/testing'
      fullPath: '/ss-admin/dataset/testing'
      preLoaderRoute: typeof SsAdminDatasetTestingImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/dataset/writer': {
      id: '/ss-admin/dataset/writer'
      path: '/ss-admin/dataset/writer'
      fullPath: '/ss-admin/dataset/writer'
      preLoaderRoute: typeof SsAdminDatasetWriterImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/settings/configsModels': {
      id: '/ss-admin/settings/configsModels'
      path: '/ss-admin/settings/configsModels'
      fullPath: '/ss-admin/settings/configsModels'
      preLoaderRoute: typeof SsAdminSettingsConfigsModelsImport
      parentRoute: typeof rootRoute
    }
    '/open/chat/': {
      id: '/open/chat/'
      path: '/open/chat'
      fullPath: '/open/chat'
      preLoaderRoute: typeof OpenChatIndexImport
      parentRoute: typeof rootRoute
    }
    '/open/copilot/': {
      id: '/open/copilot/'
      path: '/open/copilot'
      fullPath: '/open/copilot'
      preLoaderRoute: typeof OpenCopilotIndexImport
      parentRoute: typeof rootRoute
    }
    '/open/home/': {
      id: '/open/home/'
      path: '/open/home'
      fullPath: '/open/home'
      preLoaderRoute: typeof OpenHomeIndexImport
      parentRoute: typeof rootRoute
    }
    '/ss-admin/apps/': {
      id: '/ss-admin/apps/'
      path: '/ss-admin/apps'
      fullPath: '/ss-admin/apps'
      preLoaderRoute: typeof SsAdminAppsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/ss-admin/apps/flow': typeof SsAdminAppsFlowRoute
  '/ss-admin/apps/logs': typeof SsAdminAppsLogsRoute
  '/ss-admin/apps/publish': typeof SsAdminAppsPublishRoute
  '/ss-admin/apps/settings': typeof SsAdminAppsSettingsRoute
  '/ss-admin/dataset/documents': typeof SsAdminDatasetDocumentsRoute
  '/ss-admin/dataset/settings': typeof SsAdminDatasetSettingsRoute
  '/ss-admin/dataset/status': typeof SsAdminDatasetStatusRoute
  '/ss-admin/dataset/testing': typeof SsAdminDatasetTestingRoute
  '/ss-admin/dataset/writer': typeof SsAdminDatasetWriterRoute
  '/ss-admin/settings/configsModels': typeof SsAdminSettingsConfigsModelsRoute
  '/open/chat': typeof OpenChatIndexRoute
  '/open/copilot': typeof OpenCopilotIndexRoute
  '/open/home': typeof OpenHomeIndexRoute
  '/ss-admin/apps': typeof SsAdminAppsIndexRoute
}

export interface FileRoutesByTo {
  '/ss-admin/apps/flow': typeof SsAdminAppsFlowRoute
  '/ss-admin/apps/logs': typeof SsAdminAppsLogsRoute
  '/ss-admin/apps/publish': typeof SsAdminAppsPublishRoute
  '/ss-admin/apps/settings': typeof SsAdminAppsSettingsRoute
  '/ss-admin/dataset/documents': typeof SsAdminDatasetDocumentsRoute
  '/ss-admin/dataset/settings': typeof SsAdminDatasetSettingsRoute
  '/ss-admin/dataset/status': typeof SsAdminDatasetStatusRoute
  '/ss-admin/dataset/testing': typeof SsAdminDatasetTestingRoute
  '/ss-admin/dataset/writer': typeof SsAdminDatasetWriterRoute
  '/ss-admin/settings/configsModels': typeof SsAdminSettingsConfigsModelsRoute
  '/open/chat': typeof OpenChatIndexRoute
  '/open/copilot': typeof OpenCopilotIndexRoute
  '/open/home': typeof OpenHomeIndexRoute
  '/ss-admin/apps': typeof SsAdminAppsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/ss-admin/apps/flow': typeof SsAdminAppsFlowRoute
  '/ss-admin/apps/logs': typeof SsAdminAppsLogsRoute
  '/ss-admin/apps/publish': typeof SsAdminAppsPublishRoute
  '/ss-admin/apps/settings': typeof SsAdminAppsSettingsRoute
  '/ss-admin/dataset/documents': typeof SsAdminDatasetDocumentsRoute
  '/ss-admin/dataset/settings': typeof SsAdminDatasetSettingsRoute
  '/ss-admin/dataset/status': typeof SsAdminDatasetStatusRoute
  '/ss-admin/dataset/testing': typeof SsAdminDatasetTestingRoute
  '/ss-admin/dataset/writer': typeof SsAdminDatasetWriterRoute
  '/ss-admin/settings/configsModels': typeof SsAdminSettingsConfigsModelsRoute
  '/open/chat/': typeof OpenChatIndexRoute
  '/open/copilot/': typeof OpenCopilotIndexRoute
  '/open/home/': typeof OpenHomeIndexRoute
  '/ss-admin/apps/': typeof SsAdminAppsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/ss-admin/apps/flow'
    | '/ss-admin/apps/logs'
    | '/ss-admin/apps/publish'
    | '/ss-admin/apps/settings'
    | '/ss-admin/dataset/documents'
    | '/ss-admin/dataset/settings'
    | '/ss-admin/dataset/status'
    | '/ss-admin/dataset/testing'
    | '/ss-admin/dataset/writer'
    | '/ss-admin/settings/configsModels'
    | '/open/chat'
    | '/open/copilot'
    | '/open/home'
    | '/ss-admin/apps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/ss-admin/apps/flow'
    | '/ss-admin/apps/logs'
    | '/ss-admin/apps/publish'
    | '/ss-admin/apps/settings'
    | '/ss-admin/dataset/documents'
    | '/ss-admin/dataset/settings'
    | '/ss-admin/dataset/status'
    | '/ss-admin/dataset/testing'
    | '/ss-admin/dataset/writer'
    | '/ss-admin/settings/configsModels'
    | '/open/chat'
    | '/open/copilot'
    | '/open/home'
    | '/ss-admin/apps'
  id:
    | '__root__'
    | '/ss-admin/apps/flow'
    | '/ss-admin/apps/logs'
    | '/ss-admin/apps/publish'
    | '/ss-admin/apps/settings'
    | '/ss-admin/dataset/documents'
    | '/ss-admin/dataset/settings'
    | '/ss-admin/dataset/status'
    | '/ss-admin/dataset/testing'
    | '/ss-admin/dataset/writer'
    | '/ss-admin/settings/configsModels'
    | '/open/chat/'
    | '/open/copilot/'
    | '/open/home/'
    | '/ss-admin/apps/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  SsAdminAppsFlowRoute: typeof SsAdminAppsFlowRoute
  SsAdminAppsLogsRoute: typeof SsAdminAppsLogsRoute
  SsAdminAppsPublishRoute: typeof SsAdminAppsPublishRoute
  SsAdminAppsSettingsRoute: typeof SsAdminAppsSettingsRoute
  SsAdminDatasetDocumentsRoute: typeof SsAdminDatasetDocumentsRoute
  SsAdminDatasetSettingsRoute: typeof SsAdminDatasetSettingsRoute
  SsAdminDatasetStatusRoute: typeof SsAdminDatasetStatusRoute
  SsAdminDatasetTestingRoute: typeof SsAdminDatasetTestingRoute
  SsAdminDatasetWriterRoute: typeof SsAdminDatasetWriterRoute
  SsAdminSettingsConfigsModelsRoute: typeof SsAdminSettingsConfigsModelsRoute
  OpenChatIndexRoute: typeof OpenChatIndexRoute
  OpenCopilotIndexRoute: typeof OpenCopilotIndexRoute
  OpenHomeIndexRoute: typeof OpenHomeIndexRoute
  SsAdminAppsIndexRoute: typeof SsAdminAppsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  SsAdminAppsFlowRoute: SsAdminAppsFlowRoute,
  SsAdminAppsLogsRoute: SsAdminAppsLogsRoute,
  SsAdminAppsPublishRoute: SsAdminAppsPublishRoute,
  SsAdminAppsSettingsRoute: SsAdminAppsSettingsRoute,
  SsAdminDatasetDocumentsRoute: SsAdminDatasetDocumentsRoute,
  SsAdminDatasetSettingsRoute: SsAdminDatasetSettingsRoute,
  SsAdminDatasetStatusRoute: SsAdminDatasetStatusRoute,
  SsAdminDatasetTestingRoute: SsAdminDatasetTestingRoute,
  SsAdminDatasetWriterRoute: SsAdminDatasetWriterRoute,
  SsAdminSettingsConfigsModelsRoute: SsAdminSettingsConfigsModelsRoute,
  OpenChatIndexRoute: OpenChatIndexRoute,
  OpenCopilotIndexRoute: OpenCopilotIndexRoute,
  OpenHomeIndexRoute: OpenHomeIndexRoute,
  SsAdminAppsIndexRoute: SsAdminAppsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/ss-admin/apps/flow",
        "/ss-admin/apps/logs",
        "/ss-admin/apps/publish",
        "/ss-admin/apps/settings",
        "/ss-admin/dataset/documents",
        "/ss-admin/dataset/settings",
        "/ss-admin/dataset/status",
        "/ss-admin/dataset/testing",
        "/ss-admin/dataset/writer",
        "/ss-admin/settings/configsModels",
        "/open/chat/",
        "/open/copilot/",
        "/open/home/",
        "/ss-admin/apps/"
      ]
    },
    "/ss-admin/apps/flow": {
      "filePath": "ss-admin/apps/flow.tsx"
    },
    "/ss-admin/apps/logs": {
      "filePath": "ss-admin/apps/logs.tsx"
    },
    "/ss-admin/apps/publish": {
      "filePath": "ss-admin/apps/publish.tsx"
    },
    "/ss-admin/apps/settings": {
      "filePath": "ss-admin/apps/settings.tsx"
    },
    "/ss-admin/dataset/documents": {
      "filePath": "ss-admin/dataset/documents.tsx"
    },
    "/ss-admin/dataset/settings": {
      "filePath": "ss-admin/dataset/settings.tsx"
    },
    "/ss-admin/dataset/status": {
      "filePath": "ss-admin/dataset/status.tsx"
    },
    "/ss-admin/dataset/testing": {
      "filePath": "ss-admin/dataset/testing.tsx"
    },
    "/ss-admin/dataset/writer": {
      "filePath": "ss-admin/dataset/writer.tsx"
    },
    "/ss-admin/settings/configsModels": {
      "filePath": "ss-admin/settings/configsModels.tsx"
    },
    "/open/chat/": {
      "filePath": "open/chat/index.tsx"
    },
    "/open/copilot/": {
      "filePath": "open/copilot/index.tsx"
    },
    "/open/home/": {
      "filePath": "open/home/index.tsx"
    },
    "/ss-admin/apps/": {
      "filePath": "ss-admin/apps/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
