export enum ValidateType {
  None = 'None',
  Required = 'Required',
  Email = 'Email',
  Mobile = 'Mobile',
  Url = 'Url',
  Alpha = 'Alpha',
  AlphaDash = 'AlphaDash',
  AlphaNum = 'AlphaNum',
  AlphaSpaces = 'AlphaSpaces',
  Decimal = 'Decimal',
  Digits = 'Digits',
  Max = 'Max',
  MaxValue = 'MaxValue',
  Min = 'Min',
  MinValue = 'MinValue',
  Regex = 'Regex',
  Chinese = 'Chinese',
  Zip = 'Zip',
  IdCard = 'IdCard',
}

export const ValidateTypeDisplayName: Record<ValidateType, string> = {
  [ValidateType.None]: '无验证',
  [ValidateType.Required]: '字段为必填项',
  [ValidateType.Email]: '字段必须是有效的电子邮件',
  [ValidateType.Mobile]: '字段必须是有效的手机号码',
  [ValidateType.Url]: '字段必须是有效的url',
  [ValidateType.Alpha]: '字段只能包含英文字母',
  [ValidateType.AlphaDash]: '字段只能包含英文字母、数字、破折号或下划线',
  [ValidateType.AlphaNum]: '字段只能包含英文字母或数字',
  [ValidateType.AlphaSpaces]: '字段只能包含英文字母或空格',
  [ValidateType.Decimal]: '字段必须是数字',
  [ValidateType.Digits]: '字段必须是整数',
  [ValidateType.Max]: '字段不能超过指定的长度',
  [ValidateType.MaxValue]: '字段必须是数值，并且不能大于指定的值',
  [ValidateType.Min]: '字段不能低于指定的长度',
  [ValidateType.MinValue]: '字段必须是数值，并且不能小于指定的值',
  [ValidateType.Regex]: '字段必须匹配指定的正则表达式',
  [ValidateType.Chinese]: '字段必须是中文',
  [ValidateType.Zip]: '字段必须是邮政编码',
  [ValidateType.IdCard]: '字段必须是身份证号码',
}
