name: docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      working-directory: ./core
      run: dotnet restore
    - name: Build
      working-directory: ./core
      run: dotnet build ./build.sln -c Release --no-restore
